### ISSUE TITLE
Noob Here

### ISSUE THREAD

**Issue by sachasmart** [eswright/cgdi-qgis-services#30] opened 2020-02-06 05:07 UTC
Can someone please tell me how I can use this plugin? I don't see it anywhere in my menu, nor how to pull files from Open.Canada

**Comment by prushforth** [comment] 2020-02-06 21:06
Hi,  I don't know too much about this plugin yet either, but I have it installed.  Here's where to find it:

![image](https://user-images.githubusercontent.com/2437285/73978542-87777c00-48fa-11ea-9a93-9e76923398e2.png)

Once you open it, it looks like so: 

![image](https://user-images.githubusercontent.com/2437285/73978585-a83fd180-48fa-11ea-9639-2b5c17c69f4d.png)

**Comment by sachasmart** [comment] 2020-02-06 22:30
So I only these options in my menu! Any help is greatly appreciated, thank you!
![Screen Shot 2020-02-06 at 4 08 59 PM (2)](https://user-images.githubusercontent.com/56313184/73984296-5ef57f00-4906-11ea-8a51-7d97e00a8675.png)

**Comment by prushforth** [comment] 2020-02-07 18:27
To me it looks like you have yet to install the plugin.  Which you do from the Plugins menu. Or did you already do that?

**Comment by sachasmart** [comment] 2020-02-10 21:17
Yes, I have installed, uninstalled, and reinstalled a couple times!

**Comment by prushforth** [comment] 2020-02-10 21:19
What version of QGIS and the plugin are you using? I will try to repeat the steps that I did to get the plugin working per the above, and I will document them, if they aren't documented somewhere already.

**Comment by sachasmart** [comment] 2020-02-10 21:21
QGIS version:  3.10.2-A Coruña

I am running MacOS 10.15, Catalina

**Comment by prushforth** [comment] 2020-02-10 21:22
There was an issue I noticed about that config, over [here](https://github.com/eswright/cgdi-qgis-services/issues/29).  Did you notice anything like this at all?

**Comment by sachasmart** [comment] 2020-02-10 21:24
Nope, not having an issue loading layers.

**Comment by prushforth** [comment] 2020-02-10 21:25
OK i'm downloading that version now, I'll see if I can get it to work.

**Comment by prushforth** [comment] 2020-02-11 15:08
After you've installed it, does it show up in the "installed plugins" window?

![image](https://user-images.githubusercontent.com/2437285/74248942-64601a00-4cb6-11ea-8d7c-fe8c7b5293c9.png)

**Comment by sachasmart** [comment] 2020-02-11 17:14
Agh, see noob problem. I had no checked the box. But still I have now the Python error ([here](https://github.com/eswright/cgdi-qgis-services/issues/29))

**Comment by prushforth** [comment] 2020-02-11 17:16
Well that's progress at least!  I'll close this issue and try to reproduce the python error now.

**Closed as completed** 2024-03-21 03:31 UTC
